name: staging actions

on:
  push:
    branches:
      - staging
    paths:
      - 'startertheme/**'
  workflow_dispatch: 

jobs:
  deploy:
    runs-on:
      ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Write private key to file and Deploy wp-content
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          DROPLET_IP=${{ secrets.DROPLET_IP }}
          SSH_USER=${{ secrets.SSH_USER }}
          WP_CONTENT_PATH=${{ secrets.WP_CONTENT_PATH }}
          ssh -i private_key.pem -o StrictHostKeyChecking=no $SSH_USER@$DROPLET_IP "mkdir -p $WP_CONTENT_PATH"
          rsync -avz --delete \
            -e "ssh -i private_key.pem -o StrictHostKeyChecking=no" \
            startertheme/ \
            $SSH_USER@$DROPLET_IP:$WP_CONTENT_PATH
          rm private_key.pem # Remove the private key file after use
